config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  # root 'home#index'

  devise_for :users


  devise_scope :user do
    get    '/login',  to: 'devise/sessions#new'
    post   '/login',  to: 'devise/sessions#new'
    delete '/logout', to: 'devise/sessions#destroy'
  end

  # get 'sessions/new'
  # get 'users/new'
  # get '/signup', to:'users#new'
  # get    '/login',   to: 'sessions#new'
  # post   '/login',   to: 'sessions#create'
  # delete '/logout',  to: 'sessions#destroy'

  resources :users do
    member do
      get :following, :followers, :worklikes, :voicelikes
    end
  end

  resources :works do
    resources :voices, only: [:create]
  end
  resources :voices, only: [:index, :show, :destroy]

  resources :voices do
    resources :comments, only: [:create]
  end
  resources :comments, only: [:destroy]

  resources :relationships, only: [:create, :destroy]

  post 'worklike/:id' => 'work_likes#create', as: 'create_worklike'
  delete 'worklike/:id' => 'work_likes#destroy', as: 'destroy_worklike'

  post 'voicelike/:id' => 'voice_likes#create', as: 'create_voicelike'
  delete 'voicelike/:id' => 'voice_likes#destroy', as: 'destroy_voicelike'
end

app/models/work.rb
class Work < ApplicationRecord
  belongs_to :user 
  has_many :voices, dependent: :destroy 
  has_many :workLikes, dependent: :destroy
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence:true
  validates :title, presence: true, length: { maximum: 12 }
  validates :content, presence: true, length: { maximum: 1000 }
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :logged_in_user, only: [:show, :new, :create, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update, :destroy]

  def index
    @works = Work.paginate(page: params[:page])
  end

  def show
    @work = Work.find(params[:id])
    @voices = @work.voices
    @voice = current_user.voices.new
  end

  def new
    @work = current_user.works.build if user_signed_in?
  end

  def create
    @work = current_user.works.build(work_params)
    if @work.save
      flash[:notice] = "お題を投稿しました"
      redirect_to works_path
    else
      flash[:work] = @work
      flash.now[:error_messages] = @work.errors.full_messages
      render 'new'
    end
  end

  def edit
    @work = Work.find(params[:id])
  end

  def update
    @work = Work.find(params[:id])
    if @work.update(work_params)
      flash[:notice] = "募集内容を編集しました"
      redirect_to @work
    else
      flash[:work] = @work
      flash.now[:error_messages] = @work.errors.full_messages
      render 'edit'
    end
  end

  def destroy
    @work.destroy
    flash[:notice] = "お題を削除しました"
    redirect_to works_url
  end

  private

    def work_params
      params.require(:work).permit(:title, :content)
    end

    def correct_user
      @work = current_user.works.find_by(id: params[:id])
      redirect_to root_url if @work.nil?
    end

end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/works/_user_works.html.erb
<% @user.works.each do |work| %>
  <div class="<%= item %>", id="work_<%= work.id %>">
    <h3 class="<%= subTitle %> border-b-2 border-add-text border-opacity-25 mb-2">
      <%= link_to work.title, work, data: {"turbolinks" => false}  %>
    </h3>
    <p><%= work.content %></p>
    <% if current_user %>
      <div class="flex mt-6">
    
        <div class="mr-2 pr-2 border-r-2 border-add-text border-opacity-50">
          <% if current_user.workliked_by?(work.id) %>
            <%= link_to destroy_worklike_path(work), method: :DELETE, remote: true do %>
              <p>お気に入り<i class="fas fa-star pr-2"></i><%= work.workLikes.count %></p>
            <% end %>
          <% else %>
            <%= link_to create_worklike_path(work), method: :POST, remote: true do %>
              <p>お気に入り<i class="far fa-star pr-2"></i><%= work.workLikes.count %></p>
            <% end %>
          <% end %>
        </div>
    
        <div>
          <p>投稿ボイス<i class="fas fa-microphone pr-2"></i><%= work.voices.count %></p>
        </div>
    
        <div class="text-sm opacity-75 ml-auto">
          <%= link_to "…", work, data: {"turbolinks" => false} %>
        </div>
    
      </div>
    <% end %>
  </div>
<% end %>

app/views/works/_work.html.erb
<div class="<%= titleUnderLine %>">
  <h2 class="<%= subTitle %>">
    <%= link_to work.title, work, data: {"turbolinks" => false}  %>
  </h2>
</div>
<p class="opacity-75 mt-2"><%= work.content %></p>


<% if current_user %>
  <div class="flex mt-6">

    <div class="mr-2 pr-2 border-r-2 border-add-text border-opacity-50">
      <% if current_user.workliked_by?(work.id) %>
        <%= link_to destroy_worklike_path(work), method: :DELETE, remote: true do %>
          <p>お気に入り<i class="fas fa-star pr-2"></i><%= work.workLikes.count %></p>
        <% end %>
      <% else %>
        <%= link_to create_worklike_path(work), method: :POST, remote: true do %>
          <p>お気に入り<i class="far fa-star pr-2"></i><%= work.workLikes.count %></p>
        <% end %>
      <% end %>
    </div>

    <div>
      <p>投稿ボイス<i class="fas fa-microphone pr-2"></i><%= work.voices.count %></p>
    </div>

    <div class="text-sm opacity-75 ml-auto">
      <%= link_to "…", work, data: {"turbolinks" => false} %>
    </div>

  </div>
<% end %>

app/views/works/_works.html.erb
<% @user.works.each do |work| %>
  <div class="works">
    <hi class="work-title"><%= work.title %></h1>
    <p><%= work.content %></p>
  </div>
<% end %>

app/views/works/edit.html.erb
<h1 class="<%= pageTitle %>">お題内容を編集</h1>

<%= render 'shared/error_messages' %>


<%= form_with(model: @work, local: true) do |f| %>
  
  <div class="<%=form%>">
    <%= f.label :タイトル %>
    <%= f.text_field :title, class:formInput %>
  </div>

  <div class="<%=form%>">
    <%= f.label :お題詳細 %>
    <%= f.text_area :content, class:formInput  %>
  </div>

  <div class="text-count">
    <p class="work-text-count"></p>
  </div>

  <div class="<%= formBtn %>">
    <%= f.submit "編集完了", class:submit , id: "update" %>
  </div>
<% end %>

app/views/works/index.html.erb
  <h1 class="<%=pageTitle%>">投稿お題</h1>
  
  <%= will_paginate %>
  
    <% @works.each do |work| %> 
        <div class="<%= item %>", id="work_<%= work.id %>">
          <%= render 'work', work: work %>
        </div>
    <% end %>
  
  <%= will_paginate %>

app/views/works/new.html.erb
  <h1 class="<%= pageTitle %>">お題内容を記入</h1>
  
  <%= render 'shared/error_messages' %>

  <%= form_with(model: @work, local: true) do |f| %>

    <div class="<%=form%>">
      <%= f.label :タイトル, class:"text-add-text" %>
      <%= f.text_field :title, class:formInput %>
    </div>

    <div class="<%=form%>">
      <%= f.label :お題詳細, class:"text-add-text" %>
      <%= f.text_area :content, class:formInput %>
    </div>

    <div class="text-count">
      <p class="work-text-count"></p>
    </div>

    <div class="<%= formBtn %>">
      <%= f.submit "投稿する", class: submit, id:"submission" %>
    </div>

  <% end %>

app/views/works/show.html.erb
  <%= render 'shared/error_messages' %>
    
  <div class="<%= item %>">
    <div>
      <h1 class="text-add-text text-xl mb-2 text-center font-semibold lg:text-2xl <%= titleUnderLine %>">
        <%= @work.title %>
      </h1>
      
      <p class="mb-4"><%= @work.content %></p>

      <div class="text-right opacity-50">
        <% if current_user == @work.user %>
          <%= link_to "編集する", edit_work_path(@work), data: {"turbolinks" => false} %> 
          <%= link_to "削除する", @work, method: :delete, data: { confirm: "削除しますか?"} %>
        <% end %>
      </div>
    </div>
  </div>
    
  <div class="voice-form">
    <%= form_with(model: [@work, @voice], local: true) do |f| %>
      <%= f.hidden_field :work_id, value: @work.id %>
      <div class="field text-center ">
        <%= f.label :お題に投稿する, class:subTitle %>
        <%= f.file_field :voice_data, class:"mt-4" %>
      </div>
    
      <div class="<%= formBtn %> mt-4">
        <%= f.submit "ボイス投稿", class:submit, id:"submission" %>
      </div>
    <% end %> 
  </div>
  
  <div class="mt-8">
    <% @voices.each do |voice| %>
      <div class="<%= item %> flex", id="voice_<%= voice.id %>">
        <div class="w-btnPx">
          <%= image_tag voice.user.avatar.url, size: 150 %>
          <div class="text-center mt-2">
            <%= link_to voice.user.name, user_path(voice.user), data: {"turbolinks" => false}  %>
          </div>
        </div>
        
        <div class="w-2/3 ml-3 m-auto">
          <div class="px-10% pt-4">
            <%= audio_tag voice.voice_data.url %>
          </div>
          
          <div class="text-center">
            <%= link_to voice_path(voice), class: "", data: {"turbolinks" => false} do %>
              <i class="far fa-comment-alt"></i>
            <% end %>
            <%= voice.comments.count %>

            <% if current_user %>
              <% if current_user.voiceliked_by?(voice.id) %>
                <td>
                  <%= link_to destroy_voicelike_path(voice), class:"pl-4",  method: :DELETE do %>
                    <i class="fas fa-heart"></i>
                  <% end %>    
                  <%= voice.voice_likes.count %>
                </td>
              <% else %>
                <td>
                  <%= link_to create_voicelike_path(voice), class:"pl-4", method: :POST do %>
                    <i class="far fa-heart"></i>
                  <% end %>
                  <%= voice.voice_likes.count %>
                </td>
              <% end %>
            <% end %>
          </div>

          <% if current_user == voice.user %>
            <div class="text-right">
              <%= link_to '削除する', voice, method: :delete, data: { confirm: "ボイスを削除しますか?"} %>
            </div>
          <% end %>
        </div>
  
      </div>
    <% end %>
  </div>
  