config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  # root 'home#index'

  devise_for :users


  devise_scope :user do
    get    '/login',  to: 'devise/sessions#new'
    post   '/login',  to: 'devise/sessions#new'
    delete '/logout', to: 'devise/sessions#destroy'
  end

  # get 'sessions/new'
  # get 'users/new'
  # get '/signup', to:'users#new'
  # get    '/login',   to: 'sessions#new'
  # post   '/login',   to: 'sessions#create'
  # delete '/logout',  to: 'sessions#destroy'

  resources :users do
    member do
      get :following, :followers, :worklikes, :voicelikes
    end
  end

  resources :works do
    resources :voices, only: [:create]
  end
  resources :voices, only: [:index, :show, :destroy]

  resources :voices do
    resources :comments, only: [:create]
  end
  resources :comments, only: [:destroy]

  resources :relationships, only: [:create, :destroy]

  post 'worklike/:id' => 'work_likes#create', as: 'create_worklike'
  delete 'worklike/:id' => 'work_likes#destroy', as: 'destroy_worklike'

  post 'voicelike/:id' => 'voice_likes#create', as: 'create_voicelike'
  delete 'voicelike/:id' => 'voice_likes#destroy', as: 'destroy_voicelike'
end

app/views/shared/_error_messages.html.erb
<% if flash[:error_messages] %>
  <div class="">
    <ul class="">
      <% flash[:error_messages].each do |message| %>
        <li class="w-2/3 mx-error mb-4 bg-red-200 shadow py-2 border-t-2 
                   border-b-2 border-red-500 text-red-500 text-center">
          <%= message %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_head.html.erb
<title>Voice Cloud</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

<link rel="stylesheet" href="https://rsms.me/inter/inter.css" %>
<link href="https://cdn.jsdelivr.net/npm/animate.css@3.5.1" rel="stylesheet" type="text/css">
<script src="https://kit.fontawesome.com/c1baf896a0.js" crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/vue@2.6.12"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/audiojs/1.0.1/audio.min.js"    integrity="sha512-n1UxE3D0oAro7q72ZVxyGIUqB3DBt+cYVNujO4yFXm74LVPkzUUgPyP5UGEkDEDAMGLNkDo4BnIMrE/M8b5lCw==" crossorigin="anonymous"></script>
<script>
  audiojs.events.ready(function() {
    var as = audiojs.createAll();
  });
</script>

<style type="text/css" title="audiojs">
  .audiojs {
    width: 100%;
    border-radius: 0.25rem;
  }
  .audiojs .scrubber {
    display: none;
  }
  .audiojs .time {
    margin: 0;
    border: none;
  }
  .audiojs .play-pause {
    width: 37px;
  }
</style>

app/views/shared/_left.html.erb
<div class="maxLg:hidden font-sans text-sm rounded text-add-text inline-block fixed top-1/4 left-32">
  <ul class="ml-6">
    <li class="pt-4 pb-1 border-b border-add-text duration-150 ease-linear hover:bg-add-base">
      <%= link_to "プロフィール編集", edit_user_path(current_user), data: {"turbolinks" => false}, class:"m-4 my-4" %>
    </li>
    <li class="pt-4 pb-1 border-b border-add-text duration-150 ease-linear hover:bg-add-base">
      <%= link_to "お気に入りしたお題", worklikes_user_path(current_user), data: {"turbolinks" => false}, class:"m-4 my-4" %>
    </li>
    <li class="pt-4 pb-1 border-b border-add-text duration-150 ease-linear hover:bg-add-base">
      <%= link_to "いいねしたボイス", voicelikes_user_path(current_user), data: {"turbolinks" => false}, class:"m-4 my-4" %>
    </li>
    <li class="pt-4 pb-1 border-b border-add-text duration-150 ease-linear hover:bg-add-base">
      <%= link_to "ログアウト", logout_path, method: :delete, data: {"turbolinks" => false}, class:"m-4 my-4" %>
    </li>
  </ul>
</div>

app/views/shared/_right.html.erb
<div class="maxLg:hidden font-sans text-sm rounded text-add-text inline-block fixed top-1/4 right-32">
  <ul class="mr-6">
    <li class="pt-4 pb-1 border-b border-add-text duration-150 ease-linear hover:bg-add-base">
      <%= link_to "お題を探す", works_path, data: {"turbolinks" => false}, class:"m-4 my-4" %>
    </li>
    <li class="pt-4 pb-1 border-b border-add-text duration-150 ease-linear hover:bg-add-base">
      <%= link_to "お題を投稿する", new_work_path, data: {"turbolinks" => false}, class:"m-4 my-4" %>
    </li>
    <li class="pt-4 pb-1 border-b border-add-text duration-150 ease-linear hover:bg-add-base">
      <%= link_to "投稿ボイス", voices_path, data: {"turbolinks" => false}, class:"m-4 my-4" %>
    </li>
    <li class="pt-4 pb-1 border-b border-add-text duration-150 ease-linear hover:bg-add-base">
      <%= link_to "声優を探す", users_path, data: {"turbolinks" => false}, class:"m-4 my-4" %>
    </li>
  </ul>
</div>

app/views/shared/_stats.html.erb
<div class="mx-auto">
  <%= link_to "#{@user.following.count}フォロー", 
      following_user_path(@user), id:"following", data: {"turbolinks" => false}, class:"pr-2 border-r-2 border-add-text border-opacity-25" %>
  <%= link_to "#{@user.followers.count}フォロワー", 
      followers_user_path(@user), id:"follower", data: {"turbolinks" => false}, class:"pl-2"  %>
</div>